package lt.vu.menuliukai.psk.mybatis.model;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.CITY
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.EMAIL
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.NAME
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.PASSWORD
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.SURNAME
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @return the value of PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @param id the value for PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.CITY
     *
     * @return the value of PUBLIC.EMPLOYEE.CITY
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.CITY
     *
     * @param city the value for PUBLIC.EMPLOYEE.CITY
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.EMAIL
     *
     * @return the value of PUBLIC.EMPLOYEE.EMAIL
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.EMAIL
     *
     * @param email the value for PUBLIC.EMPLOYEE.EMAIL
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.NAME
     *
     * @return the value of PUBLIC.EMPLOYEE.NAME
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.NAME
     *
     * @param name the value for PUBLIC.EMPLOYEE.NAME
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.PASSWORD
     *
     * @return the value of PUBLIC.EMPLOYEE.PASSWORD
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.PASSWORD
     *
     * @param password the value for PUBLIC.EMPLOYEE.PASSWORD
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.SURNAME
     *
     * @return the value of PUBLIC.EMPLOYEE.SURNAME
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.SURNAME
     *
     * @param surname the value for PUBLIC.EMPLOYEE.SURNAME
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}