package lt.vu.menuliukai.psk.mybatis.model;

public class Office {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.OFFICE.ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.OFFICE.ADDRESS
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.OFFICE.CITY
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.OFFICE.ID
     *
     * @return the value of PUBLIC.OFFICE.ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.OFFICE.ID
     *
     * @param id the value for PUBLIC.OFFICE.ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.OFFICE.ADDRESS
     *
     * @return the value of PUBLIC.OFFICE.ADDRESS
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.OFFICE.ADDRESS
     *
     * @param address the value for PUBLIC.OFFICE.ADDRESS
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.OFFICE.CITY
     *
     * @return the value of PUBLIC.OFFICE.CITY
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.OFFICE.CITY
     *
     * @param city the value for PUBLIC.OFFICE.CITY
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }
}