package lt.vu.menuliukai.psk.mybatis.model;

public class Room {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.ADDRESS
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.SPACE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private Integer space;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.TAKEN
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private Boolean taken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.OFFICE_APARTMENT_ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private Long officeApartmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.ID
     *
     * @return the value of PUBLIC.ROOM.ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.ID
     *
     * @param id the value for PUBLIC.ROOM.ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.ADDRESS
     *
     * @return the value of PUBLIC.ROOM.ADDRESS
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.ADDRESS
     *
     * @param address the value for PUBLIC.ROOM.ADDRESS
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.SPACE
     *
     * @return the value of PUBLIC.ROOM.SPACE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public Integer getSpace() {
        return space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.SPACE
     *
     * @param space the value for PUBLIC.ROOM.SPACE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setSpace(Integer space) {
        this.space = space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.TAKEN
     *
     * @return the value of PUBLIC.ROOM.TAKEN
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public Boolean getTaken() {
        return taken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.TAKEN
     *
     * @param taken the value for PUBLIC.ROOM.TAKEN
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setTaken(Boolean taken) {
        this.taken = taken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.OFFICE_APARTMENT_ID
     *
     * @return the value of PUBLIC.ROOM.OFFICE_APARTMENT_ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public Long getOfficeApartmentId() {
        return officeApartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.OFFICE_APARTMENT_ID
     *
     * @param officeApartmentId the value for PUBLIC.ROOM.OFFICE_APARTMENT_ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setOfficeApartmentId(Long officeApartmentId) {
        this.officeApartmentId = officeApartmentId;
    }
}