package lt.vu.menuliukai.psk.mybatis.model;

import java.util.Date;

public class Trip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.LEAVING_DATE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private Date leavingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.PRICE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.RETURNING_DATE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private Date returningDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.FROM_OFFICE_ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private Long fromOfficeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.TO_OFFICE_ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    private Long toOfficeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.ID
     *
     * @return the value of PUBLIC.TRIP.ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.ID
     *
     * @param id the value for PUBLIC.TRIP.ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.LEAVING_DATE
     *
     * @return the value of PUBLIC.TRIP.LEAVING_DATE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public Date getLeavingDate() {
        return leavingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.LEAVING_DATE
     *
     * @param leavingDate the value for PUBLIC.TRIP.LEAVING_DATE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setLeavingDate(Date leavingDate) {
        this.leavingDate = leavingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.PRICE
     *
     * @return the value of PUBLIC.TRIP.PRICE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.PRICE
     *
     * @param price the value for PUBLIC.TRIP.PRICE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.RETURNING_DATE
     *
     * @return the value of PUBLIC.TRIP.RETURNING_DATE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public Date getReturningDate() {
        return returningDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.RETURNING_DATE
     *
     * @param returningDate the value for PUBLIC.TRIP.RETURNING_DATE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setReturningDate(Date returningDate) {
        this.returningDate = returningDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.FROM_OFFICE_ID
     *
     * @return the value of PUBLIC.TRIP.FROM_OFFICE_ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public Long getFromOfficeId() {
        return fromOfficeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.FROM_OFFICE_ID
     *
     * @param fromOfficeId the value for PUBLIC.TRIP.FROM_OFFICE_ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setFromOfficeId(Long fromOfficeId) {
        this.fromOfficeId = fromOfficeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.TO_OFFICE_ID
     *
     * @return the value of PUBLIC.TRIP.TO_OFFICE_ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public Long getToOfficeId() {
        return toOfficeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.TO_OFFICE_ID
     *
     * @param toOfficeId the value for PUBLIC.TRIP.TO_OFFICE_ID
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    public void setToOfficeId(Long toOfficeId) {
        this.toOfficeId = toOfficeId;
    }
}