package lt.vu.menuliukai.psk.mybatis.dao;

import java.util.List;
import lt.vu.menuliukai.psk.mybatis.model.Employee;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    Employee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    int updateByPrimaryKey(Employee record);
}