package lt.vu.menuliukai.psk.mybatis.dao;

import java.util.List;
import lt.vu.menuliukai.psk.mybatis.model.Office;

public interface OfficeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OFFICE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OFFICE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    int insert(Office record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OFFICE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    Office selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OFFICE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    List<Office> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OFFICE
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    int updateByPrimaryKey(Office record);
}