package lt.vu.menuliukai.psk.mybatis.dao;

import java.util.List;
import lt.vu.menuliukai.psk.mybatis.model.Trip;

public interface TripMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    int insert(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    Trip selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    List<Trip> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Sun Apr 28 13:23:06 EEST 2019
     */
    int updateByPrimaryKey(Trip record);
}